version: 2.1
jobs:
  build-docs:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: Build docs
          command: |
            cd docs
            pip install -r requirements.txt
            make html
  run-tests:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - run:
          name: Run tests and update thumbnails
          command: |
            cd ..
            npm install .
            npm test

workflows:
  version: 2
  Full_Build:
    jobs:
      - build-docs
      - run-tests:
          requires:
            - build-docs
