version: 2.1
jobs:
  build-docs:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Build docs
          command: |
            cd brainsprite
            sudo apt install npm
            sudo npm install -g jsdoc
            pip install --progress-bar off -e .
            cd ../docs
            pip install --progress-bar off -r requirements.txt
            make html
      - persist_to_workspace:
          root: .
          paths:
            - tests
            - docs
  run-tests:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run tests and update thumbnails
          command: |
            npm install .
            npm test
            mkdir /tmp/test_report
            cp tests/plot_*.png /tmp/test_report
      - store_artifacts:
          path: /tmp/test_report
          destination: circleci-tests
      - persist_to_workspace:
          root: .
          paths:
            - docs
  deploy-docs:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Deploy website on brainsprite.github.io
          command: |
            echo Cloning brainsprite.github.io
            git config --global user.email "$GH_EMAIL" > /dev/null 2>&1
            git config --global user.name "$GH_NAME" > /dev/null 2>&1
            git clone https://brainsprite-bot:$TOKEN@github.com/brainsprite/brainsprite.github.io.git website > /dev/null 2>&1
            echo Scrapping old website and updating content
            rm -rf website/*
            cp -r docs/build/html/* website/
            echo Committing updated website
            cd website
            touch .nojekyll
            git add *
            git add .nojekyll 
            git commit --all -m "Automated update through circleci"
            git push --force --quiet origin master

workflows:
  version: 2
  Full_Build:
    jobs:
      - build-docs
      - run-tests:
          requires:
            - build-docs
      - deploy-docs:
          filters:
            branches:
              only:
                - master
          context: docs-build
          requires:
            - run-tests
