version: 2.1
jobs:
  build-docs:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Build docs
          command: |
            cd docs
            pip install --progress-bar off -r requirements.txt
            make html
      - persist_to_workspace:
          root: .
          paths:
            - tests
            - docs
  run-tests:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run tests and update thumbnails
          command: |
            npm install .
            npm test
      - store_artifacts:
          path: tests
          destination: circleci-tests
      - store_artifacts:
          path: docs/build/html
          destination: circleci-docs

workflows:
  version: 2
  Full_Build:
    jobs:
      - build-docs
      - run-tests:
          requires:
            - build-docs
