---
name: test

on:
    push:
        branches:
        -   main
        -   master
    pull_request:
        branches:
        -   '*'
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

# Force to use color
env:
    FORCE_COLOR: true

jobs:

    test_js:

        name: Test Javascript

        runs-on: ubuntu-latest

        steps:

        -   uses: actions/checkout@v4
        -   uses: actions/setup-node@v4
            with:
                node-version: 18  
        -   name: Install Puppeteer dependencies
            run: |
                sudo apt-get update
                sudo apt-get install -y \
                    ca-certificates \
                    fonts-liberation \
                    libasound2 \
                    libatk-bridge2.0-0 \
                    libatk1.0-0 \
                    libc6 \
                    libcairo2 \
                    libcups2 \
                    libdbus-1-3 \
                    libexpat1 \
                    libfontconfig1 \
                    libgbm1 \
                    libgcc1 \
                    libglib2.0-0 \
                    libgtk-3-0 \
                    libnspr4 \
                    libnss3 \
                    libpango-1.0-0 \
                    libpangocairo-1.0-0 \
                    libstdc++6 \
                    libx11-6 \
                    libx11-xcb1 \
                    libxcb1 \
                    libxcomposite1 \
                    libxcursor1 \
                    libxdamage1 \
                    libxext6 \
                    libxfixes3 \
                    libxi6 \
                    libxrandr2 \
                    libxrender1 \
                    libxss1 \
                    libxtst6 \
                    lsb-release \
                    wget \
                    xdg-utils          
        -   name: Install
            run: npm install
        -   name: Run test suite
            run: npm test

